### ISSUE TITLE
Permission problems

### ISSUE THREAD

**Issue by sql-aus-hh** [OpenQueryStore/OpenQueryStore#15]
Just ran another test on my Windows 2012 R2 with SQL Server 2008 R2 Express Edition (10.50.4000.0)

The activated proc '[oqs].[ActivateOQSScheduler]' running on queue 'AdventureWorks2008R2.dbo.OQSScheduler' output the following:  'Cannot execute as the database principal because the principal "dbo" does not exist, this type of principal cannot be impersonated, or you do not have permission.'

Installed with installer_classic and certificate...

**Comment by sql-williamd** [comment]
We have redesigned things and updated the installer and documentation around the installer process. Can you download the latest version and test please?

**Comment by sql-williamd** [comment]
Closing this bug now. We are not seeing the issue on our test builds. Please re-open if you are still having issues

**Comment by Evdlaar** [comment]
Even though this issue is marked as fixed we have found the problem that causes this issue.
This message can occur in the error log if the database that has the OQS installed does not have a owner set on the database.
Configuring a owner should resolve the error message and will start the OQS collection.
