### ISSUE TITLE
Personalised benign waits

### ISSUE THREAD

**Issue by fatherjack** [OpenQueryStore/OpenQueryStore#56]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x] *feature* 
- [ ] *bug*:

## Instance Details
In some cases (installations) certain wait types are always present and as such need to be filtered out as noise from performance reports. It is possible however that in one installation these same wait types are not common and should be highlighted when collected by OQS.

Can we add a feature to allow each installation to configure a list of wait types that should be masked in addition to the benign waits listed at https://github.com/OpenQueryStore/OpenQueryStore/wiki/BenignWaits ? This would allow each site to have a better view of their own problematic wait types.

**Comment by Splaxi** [comment]
What about a switch/parameter in the install script? -CustomExcludeWaitTypes "c:\Temp\WaitTypes.txt" 

Otherwise we could put our current list of waittypes into a txt file, that we use when installing. That way people would only have to know of the file and edit it, before installing. The file can then be stored in a central repository within the company and shared across multiple installations.

**Comment by sql-williamd** [comment]
fixed with latest commit (should have used "close" in the commit to auto-close this issue)
