### ISSUE TITLE
Primary Key violation in oqs.query_runtime_stats

### ISSUE THREAD

**Issue by cairneym** [OpenQueryStore/OpenQueryStore#57]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [ X] *bug*:

## Instance Details
Run the following instruction on your SQL Server instance:
```SQL 
SELECT @@VERSION 
```
and paste the output here
- SQL Server version and edition: _<result of execution>_
Microsoft SQL Server 2012 (SP3) (KB3072779) - 11.0.6020.0 (X64)   Oct 20 2015 15:36:27   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.2 <X64> (Build 9200: ) (Hypervisor) 

## Steps to Reproduce

Manually executed the procedure [oqs].[gather_statistics] with Debug = 1 and LogMode = 1

This threw an error:  

Msg 2627, Level 14, State 1, Line 179
Violation of PRIMARY KEY constraint 'pk_query_runtime_stats'. Cannot insert duplicate key in object 'oqs.query_runtime_stats'. The duplicate key value is (5506, 1).

On diving in to this I found that there was 2 rows in [oqs].[queries] which had the same values for query_hash and creation_time but had different plan_id and query_id:

query_id|plan_id|query_hash|query_plan_MD5|query_statement_start_offset|query_statement_end_offset|query_creation_time
--------|-------|----------|--------------|---------------------------|--------------------------|-------------------
5506|1239|0xD89D521F2F638D1A|0x5796D78EE89B909339001CC061129C61D89D521F2F638D1A|0|-1|2017-11-14 11:05:44.757
14458|1622|0xD89D521F2F638D1A|0xE6F91538479DA21E50FFBCEA00FB59D9D89D521F2F638D1A|0|-1|2017-11-14 11:05:44.757

When this is joined to the [oqs].[query_stats] view then there are two rows generated for each of the query_id values and the Primary Key is violated.

**Comment by planforwar** [comment]
this seems  to fix it:
ALTER TABLE [oqs].[query_runtime_stats] DROP CONSTRAINT [pk_query_runtime_stats] WITH ( ONLINE = OFF )
GO
ALTER TABLE [oqs].[query_runtime_stats] ADD  CONSTRAINT [pk_query_runtime_stats] PRIMARY KEY CLUSTERED 
(
	[query_id] ASC,
	[interval_id] ASC
)WITH (IGNORE_DUP_KEY = ON) ON [PRIMARY]
GO

**Comment by sql-williamd** [comment]
Hi @planforwar - ignoring the Primary Key with ignore_dup_key is not what we want to aim for. It defeats the purpose of a PK if we do that.

What is more confusing is the query_hash collision. This shouldn't happen, but evidently does.

I will have to defer to @Evdlaar because the hashing part is his. I want to say this is a "one off" cos hash collisions really should be rare...... Enrico, ideas?

**Comment by Zindur** [comment]
I was able to replicate as well and getting same error: Violation of PRIMARY KEY constraint 'pk_query_runtime_stats'. Cannot insert duplicate key in object 'oqs.query_runtime_stats'

Installation mode: -OQSMode Centralized

Monitoring few similar Databases (5) with same schemas and objects (procedures, functions,...)

**Comment by planforwar** [comment]
it isn't hash collision, it is valid for a query to have more than one plan (which then has it's own stats). So the query hash will appear for each plan. The way to resolve that is normalizing the table structure or grouping the stats at query level (which wouldn't accurate because you might disguise the stats for a bad plan). In the meantime allowing duplicates resolves the issue.

**Comment by Evdlaar** [comment]
We are looking into this atm.
The query hash is the hash that belongs to the query statement and is generated by SQL Server itself. Even if multiple identical hashes occur the query_id should still be unique, like in the example screenshots. I am guessing we are joining somewhere on the query hash to process or gather data.

Basically we want one unique ID per query and per plan and link to those. This would avoid situations like this I think. Apperently we have some logic somewhere that avoids this wanted behaviour.

**Comment by planforwar** [comment]
The query id is unique in the queries table, however when the proc gathers query stats at line 197 it joins on the query hash:
INSERT INTO [oqs].[query_runtime_stats]
...
FROM   [oqs].[queries] AS [oqs_q]
	INNER JOIN [oqs].[query_stats] AS [qs] 
		ON 
			(  
				**[oqs_q].[query_hash] = [qs].[query_hash]**
				AND [oqs_q].[query_statement_start_offset] = [qs].[statement_start_offset]
				AND [oqs_q].[query_statement_end_offset] = [qs].[statement_end_offset]
				AND [oqs_q].[query_creation_time] = [qs].[creation_time]
			);

Because SQL Server keeps stats for each execution plan for each query, the query hash will be duplicated. That is valid output from dm_exec_query_stats. Having duplicate query ids in the query_runtime_stats is valid. If you really want to have "proper" primary keys it will need a junction table. I honestly don't think it matters that much though to be honest.

**Comment by Evdlaar** [comment]
Out of curiosity: do you run into this issue while using OQS in combination with multiple databases inside the same SQL Server Instance that have a more-or-less identical workload (e.g. a Test and Development DB where more or less the same query statements are being executed against)? 

Thanks!

**Comment by planforwar** [comment]
No, I have this on one server looking at one database at the moment (in a test environment) using the centralised deployment. The overhead of the collection is quite high (it looks to be the XML.nodes section causing this, I think a replacement CLR function will resolve that), so I'm looking to tune that before deploying to production servers.
I'm happy to share any improvements I make.

**Comment by Evdlaar** [comment]
Alright thanks for the feedback!
Yes, if there are many plans in the plan cache the XML shredding causes some overhead, especially during the first collection. We are also looking at ways to optimize that.
Regarding this issue, we will be making changes to the primary key in the next release and are testing that now.

**Comment by JanosBerke** [comment]
I was also experiencing this, but since the last version (2.1.0) it works fine so far. The only difference was in the QueryPlan node, RelOps were identical for both plans. We are using the same ANSI settings and I am still investigating the same plans with multiple times with different plan_handle.

**Comment by sql-williamd** [comment]
This may be fixed in the latest release. Monitoring for the next few weeks then closing as fixed

**Comment by TheRockStarDBA** [comment]
is this still an issue @sql-williamd ?
